name: Build & Test
on: [push]

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    container: tonyodell/rakudo-nightly:latest
    steps:
      - name: os deps
        run: |
          apt update && \
          apt install -y git
      - name: clone
        uses: actions/checkout@v3
      - name: module deps
        run: zef install --deps-only --debug .
      - name: test & installs ok
        run: zef install .
